version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: garden-shop-db
    environment:
      POSTGRES_DB: garden-shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: predators
    ports:
      - "5432:5432"
    networks:
      - garden-net
    restart: always

  frontend:
    build: ../garden-shop-frontend/
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://garden-shop:8080/v1 # Пример переменной окружения для доступа к бэкенду
    depends_on:
      - garden-shop
    networks:
      - garden-net


  garden-shop:
    # image: garden-shop # Закомментируйте или удалите эту строку
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/garden-shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: predators
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - garden-net
    restart: always

networks:
  garden-net:
    driver: bridge